language: node_js
node_js:
  - 8.2.0
addons:
  postgresql: 9.6
services:
  - postgresql
before_script:
  - psql -U postgres -c 'create database biosentiers;'
  - psql -U postgres -c 'create extension postgis;' biosentiers
  - npm run migrate:test
env:
  - NODE_ENV=test SECRET=travis
